name: codecov
version: 1.0.0
description: Generates lcov and/or HTML coverage reports for Dart projects. (UNIX only)
homepage: https://github.com/codecov/dart
dependencies:
  args: "^2.0.0"
  logging: ">=0.9.0 <1.1.0"
  path: "^1.6.3"
environment:
  sdk: ">=2.12.0-0 <2.14.0"
dev_dependencies:
  coverage: "0.13.11"
  test: "1.12.0"
executables:
  codecov:
  generate_coverage:
